### ISSUE TITLE
Stubs for the classes for widget based on a model

### ISSUE THREAD

**Issue by fasteddys** [jdanylko/Tuxboard#22]
Hello, this is a fav. lib of mine, I am trying to create an auto generate function that creates the classes for the widgets and the dashboard, can you share what are the classes I should be generating.

Or would it be better to have a base class with all the classes and relationships and derive from it?

**Comment by jdanylko** [comment]
Since the widgets are simply ViewComponents, you have a couple of options:

1. Create a BaseViewComponent (or BaseWidget) and using dependency injection, inject what you need into the component. For example, I have an Approval widget in my CMS for assets that need approval from other people. I automatically inject a service into the component to grab the approvals.

`    [ViewComponent(Name="approval")]
    public class ApprovalViewComponent : ViewComponent
    {
        private readonly IApprovalService _approvalService;

        public ApprovalViewComponent(IApprovalService approvalService)
        {
            _approvalService = approvalService;
        }

        public async Task<IViewComponentResult> InvokeAsync(WidgetPlacement placement)
        {
            var approvals = await _approvalService.GetApprovalSummaryAsync();

            var model = new ApprovalModel
            {
                Placement = placement,
                Approvals = approvals.ToList()
            };

            foreach (var item in model.Approvals)
            {
                item.Uri = item.ContentName == "Assets" 
                    ? new Uri(Url.AssetsUrl(), UriKind.Relative) 
                    : new Uri(Url.ContentTypesUrl(item.ContentTypeId), UriKind.Relative);
            }

            return View("Default", model);
        }
    }
`
Once I have the data access class (IApprovalService), I can populate it as necessary. Your BaseWidget could inject everything you need for your base widgets.

2. Once you have a generic widget created, you could easily create a item template. In Visual Studio (proper, not Code), you can do "Project / Export Template..." for your BaseWidget class and then perform a File / New... and pick your BaseWidget from the list (Ref: [How to: Create item templates](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2022) )

3. and there's always the "poor man's code generator", the T4. This could automatically create code for you based on a template? [5 Methods of Generating Code Using Microsoft Tools](https://www.danylkoweb.com/Blog/5-methods-of-generating-code-using-microsoft-tools-FS)

I hope this helps.

**Comment by jdanylko** [comment]
If your data is generic enough, I would encapsulate it more at the ViewComponent level.

In your ViewComponent (Widget?), I would pass the data into the ViewComponent's "Default.cshtml" View. I like to do things declaratively as opposed to writing code to create a UI (like the HTMLTable) If I need to make a UI change, I like to make it without re-compiling. ;-)

```
public class TableWidget : Widget
{
    private readonly ITableDataService _tableDataService;

    public TableWidget(ITableDataService tableDataService)
    {
        _tableDataService = tableDataService;
    }

    public IViewComponentResult Invoke()
    {
        return this.WidgetView(new TableWidgetModel{ Content = _tableDataService.GetData() } );
    }
}
```
In the Default.cshtml, add the Model.
```
@model TableWidgetModel
```
And then create your table using HTML.

[One example](https://github.com/jdanylko/Tuxboard/tree/master/UserSpecificDashboard/TuxboardFeature/Widgets/Table)

I was told a while ago that ViewComponents are like "mini-controllers." Yes, you can pass things into them, but it makes more sense to contain everything in each ViewComponent.

So your Controller can be whittled down to a View instead of passing data. Your Controller's View will have your markup and a ViewComponent widget:
```
<div class="widget">
   <vc:TableWidget />
</div>
```

I hope this helps and thank you so much for the support.

The references I've been using for building ViewComponents for Tuxboard:
- [Microsoft ViewComponents](https://learn.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-7.0)
- [6 Reasons To Use ViewComponents](https://www.danylkoweb.com/Blog/6-reasons-to-use-viewcomponents-in-aspnet-5-S3)
- [Quick Tip: How to load ViewComponents in Razor Pages](https://www.danylkoweb.com/Blog/quick-tip-how-to-load-viewcomponents-in-razor-pages-S2) (this will be important in a future post about Tuxboard) ;-)

**Comment by jdanylko** [comment]
Awesome! Glad to hear it's coming together for you.

For permissions, I use Microsoft Identity to identify user types coming into the system and what widgets they can add/see/use onto a dashboard.

I've even adapted a similar strategy for any type of [menu system using Microsoft Identity](https://www.danylkoweb.com/Blog/updating-the-menu-system-to-aspnet-core-31-with-microsoft-identity-N7); What menu items can you show/hide based on a user's role.

If you look at the [HomeController.cs](https://github.com/jdanylko/Tuxboard/blob/master/UserSpecificDashboard/Controllers/HomeController.cs) for the "kitchen sink" demo, you'll see a `GetCurrentUser()` to retrieve the current user logged in. Once you know who this is, you can read the tables and their roles. This allows you to pull certain widgets based on roles. This is where the [database tables](https://github.com/jdanylko/Tuxboard/wiki/Architecture-(back-end)) WidgetPlan, DashboardDefault, and Dashboard tables come into play. They can be renamed to WidgetRoles for roles instead, but with a couple of projects I wrote in the past, they used User Plans (like [multi-tier subscriptions](https://www.danylkoweb.com/Blog/creating-multi-tier-subscriptions-using-c-T3)).

Hope this helps. :-)
